// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HyperPOS.Models;

public partial class MenuItem
{
    public Guid Id { get; set; }

    public Guid? MenuId { get; set; }

    public string Name { get; set; }

    public string Category { get; set; }

    public decimal Price { get; set; }

    public string Unit { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<RecipeItem> RecipeItems { get; set; } = new List<RecipeItem>();
}