// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HyperPOS.Models;

public partial class OrderItem
{
    public int Id { get; set; }

    public Guid? OrderId { get; set; }

    public Guid? MenuItemId { get; set; }

    public int Quantity { get; set; }

    public string Note { get; set; }

    public virtual MenuItem MenuItem { get; set; }

    public virtual Order Order { get; set; }
}