// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HyperPOS.Models;

public partial class Order
{
    public Guid Id { get; set; }

    public Guid? TenantId { get; set; }

    public Guid? BranchId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? TableId { get; set; }

    public string Status { get; set; }

    public decimal? Total { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual CafeTable Table { get; set; }

    public virtual Tenant Tenant { get; set; }

    public virtual User User { get; set; }
}