// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HyperPOS.Models;

public partial class RecipeItem
{
    public Guid Id { get; set; }

    public Guid? MenuItemId { get; set; }

    public Guid? IngredientId { get; set; }

    public decimal Quantity { get; set; }

    public virtual Ingredient Ingredient { get; set; }

    public virtual MenuItem MenuItem { get; set; }
}