// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HyperPOS.Models;

public partial class StockMovement
{
    public Guid Id { get; set; }

    public Guid? BranchId { get; set; }

    public Guid? IngredientId { get; set; }

    public decimal Quantity { get; set; }

    public string Type { get; set; }

    public string Source { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Ingredient Ingredient { get; set; }
}