// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HyperPOS.Models;

public partial class User
{
    public Guid Id { get; set; }

    public Guid? TenantId { get; set; }

    public Guid? BranchId { get; set; }

    public string Username { get; set; }

    public string Role { get; set; }

    public string PinCode { get; set; }

    public bool? Active { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Tenant Tenant { get; set; }
}